# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: publish pvcf pinaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# permissions:
#   contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: create a binary realease for mac
      run: |
        pyinstaller pvcf.py
    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v4.3.3
    #   with:
    #     name: pvcf-mac
    #     # A file, directory or wildcard pattern that describes what to upload
    #     path: ./dist/pvcf/pvcf
    - name: Upload release artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@v2
      with:
        args: "dist/pvcf/ "
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
